# Generated by Django 3.2 on 2023-05-26 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_shopping_cart_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления в корзину')),
            ],
            options={
                'verbose_name': 'Рецепт в корзине',
                'verbose_name_plural': 'Рецепты в корзине',
                'ordering': ('add_to_shopping_cart_date',),
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_favorite_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления в избранное')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
                'ordering': ('add_to_favorite_date',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название ингредиента', max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название ингредиента')),
                ('measurement_unit', models.CharField(help_text='Введите единицу измерения', max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумайте название рецепта', max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='Invalid recipe name', message='Имя может содержать только буквы!', regex='^[А-Яа-я ,]+$')], verbose_name='Название')),
                ('image', models.ImageField(upload_to='recipes/images/', verbose_name='Картинка')),
                ('text', models.TextField(help_text='Опишите рецепт', verbose_name='Описание')),
                ('cooking_time', models.SmallIntegerField(help_text='Введите время приготовления рецепта', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления (в минутах)')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Придумай название для тега', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='Invalid tag name', message='Название тега может быть написанотолько кириллицей. Могут использоваться только буквы и пробелы.', regex='^[А-Яа-я ]+$')], verbose_name='Название')),
                ('color', models.CharField(help_text='Пропишите цвет в HEX формате', max_length=7, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(code='Invalid tag HEX color', message='Цвет должен начинаться с символа # и может состоять только из цифр 0-9и латинских букв A-F или a-f. Длина 4 или 7 символов.', regex='^#[0-9A-Fa-f]{3}$|^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(help_text='Введите слаг тега', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(code='Invalid tag slug', message='Слаг тега может быть написантолько латиницей. Могут использоваться только нижние подчеркивания.', regex='^[A-Za-z_]+$')], verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Кол-во ингредиента в рецепте',
                'ordering': ('recipe', 'ingredient'),
            },
        ),
    ]
