# Generated by Django 3.2 on 2023-05-26 21:02

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230526_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения', max_length=200, validators=[core.validators.MinMeasurementUnitLenghtValidator(1), core.validators.CyrillicCharRegexValidator()], verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Напишите название ингредиента', max_length=200, validators=[core.validators.MinTwoCharValidator(2), core.validators.CyrillicCharRegexValidator()], verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(help_text='Введите время приготовления рецепта', validators=[core.validators.MinCookingTimeValueValidator(1)], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Придумайте название рецепта', max_length=200, validators=[core.validators.MinTwoCharValidator(2), core.validators.CyrillicCharRegexValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.SmallIntegerField(validators=[core.validators.MinIngredientAmountValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Пропишите цвет в HEX формате', max_length=7, validators=[core.validators.MinTagColorLenghtValidator(4), core.validators.TagColorRegexValidator()], verbose_name='Цвет в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Придумай название для тега', max_length=200, unique=True, validators=[core.validators.MinTwoCharValidator(2), core.validators.CyrillicCharRegexValidator()], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите слаг тега', max_length=200, unique=True, validators=[core.validators.MinTwoCharValidator(2), core.validators.TagSlagRegexValidator()], verbose_name='Уникальный слаг'),
        ),
    ]
