# Generated by Django 3.2 on 2023-05-26 21:02

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите ваше имя!', max_length=150, validators=[core.validators.MinTwoCharValidator(2), core.validators.CyrillicCharRegexValidator()], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите вашу фамилию', max_length=150, validators=[core.validators.MinTwoCharValidator(2), core.validators.CyrillicCharRegexValidator()], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Придумате юзернейм!', max_length=150, unique=True, validators=[core.validators.MinTwoCharValidator(2), core.validators.UserUsernameRegexValidator()], verbose_name='Юзернейм'),
        ),
    ]
