# Generated by Django 3.2 on 2023-05-30 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230529_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_in_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Автор в подписке'),
        ),
    ]
